debug: true
# Server settings
server:
    port: 9001
#    address: localhost

#security:
#  user:
#    password: user
#  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
#  sessions: ALWAYS
#  oauth2:
#    sso:
#      loginPath: /dashboard/login
#management:
#  security:
#    role: HERO
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#    com.netflix.discovery: 'OFF'

# DATASOURCE
#jdbc:
#    dataSourceClassName: com.mysql.jdb.Driver
#    url: jdbc:mysql://rdsqbjjbe2evein.mysql.rds.aliyuncs.com:3306/edu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#    databaseName: test
#    serverName: aliyun
#    username: grow
#    password: Grow2015
#    cachePrepStmts: true
#    prepStmtsSize: 250
#    prepStmtsCacheSqlLimit: 2048
#    userServerPrepStmts: true

# SPRING PROFILES
spring:       
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
      # platform: mysql
        url: jdbc:mysql://rdsqbjjbe2evein.mysql.rds.aliyuncs.com:3306/bluepx-edu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: grow
        password: Grow2015
#        url: jdbc:mysql://192.168.99.100:3306/bluepx-edu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#        username: admin
#        password: abcd1234
#  security:
#    oauth2:
#      client:
#        accessTokenUri: http://localhost:8080/uaa/oauth/token
#        userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
#        clientId: acme
#        clientSecret: acmesecret
#      resource:
#        jwt:
#          keyValue: |
#            -----BEGIN PUBLIC KEY-----
#            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
#            -----END PUBLIC KEY-----
#        id: openid
#        serviceId: ${PREFIX:}resource
# MyBatis
#mybatis:
#    typeAliasesPackage: com.atdld.os.entity,com.atdld.os.api.help.entity
#    mapperLocations: classpath:/mybatis/**/*Mapper.xml
#    configLocation: classpath:/SqlMapConfig.xml
# LOGGING
logging:
    level:
       com.ibatis:INFO