server:
     port: 8080
logging.level.org.springframework.security: DEBUG
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
      # platform: mysql
        url: jdbc:mysql://rdsqbjjbe2evein.mysql.rds.aliyuncs.com:3306/bluepx-edu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: grow
        password: Grow2015
    jpa:
#       database-platform: org.hibernate.dialect.MySQL5Dialect
        database: MYSQL
        hibernate:
            ddl-auto: validate
        openInView: false
        show_sql: true

    security:
      oauth2:
      client:
        accessTokenUri: http://localhost:8080/oauth/token
#             generate-ddl: false
#         security:
#            oauth2:
#            client:
#              accessTokenUri: http://localhost:8080/uaa/oauth/token
#              userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
#              clientId: acme
#              clientSecret: acmesecret
#            resource:
#              jwt:
#                keyValue: |
#                  -----BEGIN PUBLIC KEY-----
#                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
#                  -----END PUBLIC KEY-----
#             id: openid
#             serviceId: ${PREFIX:}resource